routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

use App\Http\Controllers\LabTestResultController;
use App\Http\Controllers\PatientController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PhysicianController;
use App\Http\Controllers\ResultController;
use App\Http\Controllers\BrandController;
use App\Http\Controllers\SpecimenController;
use App\Http\Controllers\TestController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\SettingController;

// Route::get('/mail/{id}', [LabTestResultController::class, 'mail_test'])->name('mail_test');


Route::middleware(['auth'])->group(function () {
    Route::get('/', function () {
        return view('layout.app');
    });


    Route::group(['middleware' => ['role:pathologist']], function () {
        Route::group(['prefix' => 'settings', 'as' => 'settings.'], function () {
            Route::get('/', [SettingController::class, 'index'])->name('index');
            Route::post('/update-facility', [SettingController::class, 'updateFacility'])->name('updateFacility');
            Route::post('/update-logo', [SettingController::class, 'updateLogo'])->name('updateLogo');
            Route::post('/update-auto-approve', [SettingController::class, 'updateAutoApprove'])->name('updateAutoApprove');
        });
        Route::resource('/users', UserController::class);
        Route::resource('/results', ResultController::class);
        Route::resource('/brands', BrandController::class);
        Route::resource('/specimens', SpecimenController::class);
        Route::resource('/tests', TestController::class);

        Route::group(['prefix' => 'lab-tests', 'as' => 'labTests.'], function () {
            Route::get('/', [LabTestResultController::class, 'index'])->name('index');
            Route::put('/{id}/approve', [LabTestResultController::class, 'approve'])->name('approve');
        });
    });
    Route::group(['middleware' => ['role:pathologist|medTech']], function () {
        Route::resource('/patients', PatientController::class);
        Route::group(['prefix' => 'patients', 'as' => 'patients.'], function () {
            Route::get('/{id}/vaccinations/', [PatientController::class, 'index_vax'])->name('index_vax');
            Route::get('/{id}/vaccinations/create', [PatientController::class, 'create_vax'])->name('create_vax');
            Route::post('/{id}/vaccinations/store', [PatientController::class, 'store_vax'])->name('store_vax');
            Route::get('/{id}/vaccinations/{vax_id}/edit', [PatientController::class, 'edit_vax'])->name('edit_vax');
            Route::put('/{id}/vaccinations/{vax_id}/update', [PatientController::class, 'update_vax'])->name('update_vax');
        });
        Route::resource('/physicians', PhysicianController::class);
        Route::group(['prefix' => 'lab-tests', 'as' => 'labTests.'], function () {
            Route::get('/', [LabTestResultController::class, 'index'])->name('index');
            Route::get('/{id}/show', [LabTestResultController::class, 'show'])->name('show');
            Route::get('/{id}/mail', [LabTestResultController::class, 'mail_patient'])->name('mail_patient');
            Route::put('/{id}/to-validate', [LabTestResultController::class, 'to_validate'])->name('to_validate');
        });
    });

    Route::group(['middleware' => ['role:medTech']], function () {

        Route::group(['prefix' => 'lab-tests', 'as' => 'labTests.'], function () {

            Route::get('/create', [LabTestResultController::class, 'create'])->name('create');
            Route::post('/store', [LabTestResultController::class, 'store'])->name('store');
            Route::get('/{id}/edit', [LabTestResultController::class, 'edit'])->name('edit');
            Route::put('/{id}/update', [LabTestResultController::class, 'update'])->name('update');
            Route::delete('/{id}/delete', [LabTestResultController::class, 'delete'])->name('delete');
        });
    });
});

Route::get('/{key}/pdf', [LabTestResultController::class, 'pdf'])->name('pdf');
Route::get('lab-tests/{key}/verify', [LabTestResultController::class, 'verify'])->name('verify');

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;
use Illuminate\Database\Eloquent\SoftDeletes;


class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, HasRoles, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'first_name',
        'middle_name',
        'last_name',
        'prc_no',
        'position',
        'signature'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(User $user)
    {
        return view('users.form', compact('user'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $path = $request->file('esign')->store('esign');
        $request->merge(['name' => $request->first_name . " " . $request->last_name, 'signature' => $path, 'password' => bcrypt($request->password)]);
        $user = User::create($request->except('_token'));
        if ($request->role === 'P') {
            $user->assignRole('pathologist');
            $user->syncPermissions(['edit lab_result details', 'approve']);
        } else {

            $user->assignRole('medTech');
            $user->syncPermissions(['edit lab_result details', 'encode']);
        }
        return redirect(\route('users.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('users.form', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        if ($request->has('esign')) {

            $path = $request->file('esign')->store('esign');
            $request->merge(['signature' => $path]);
        }
        $request->merge(['password' => bcrypt($request->password)]);
        $user->update($request->except('_token', 'role'));
        $user->removeRole($user->getRoleNames()[0]);
        if ($request->role === 'P') {
            $user->assignRole('pathologist');
            $user->syncPermissions(['edit lab_result details', 'approve']);
        } else {

            $user->assignRole('medTech');
            $user->syncPermissions(['edit lab_result details', 'encode']);
        }
        return redirect(\route('users.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        User::destroy($user->id);
        return redirect(\route('users.index'));
    }
}

resources/views/users/form.blade.php
@extends('layout.app')

@section('content')
<nav aria-label="Page breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item" aria-current="page"><a href="{{route('users.index')}}">Users</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{isset($user->id) ? 'Update' : 'Add new' }} </li>
    </ol>
</nav>
<div class="app-card shadow-sm mb-4 border-left-decoration">
    <div class="inner">
        <div class="app-card-body p-4">
            <form action="{{isset($user->id) ? route('users.update', $user->id) :route('users.store')}}" method="post" enctype="multipart/form-data">
                <div class="row gx-5 gy-3">
                    <div class="col-md-6 ">
                        @csrf
                        @if(isset($user->id))
                        @method('PUT')
                        @endif
                        <div class="row">
                            <div class="form-group">
                                <label for="first_name">First Name:</label>
                                <input id="first_name" class="form-control" value="{{old('first_name', $user->first_name)}}" type="text" name="first_name" placeholder="Juan" required>
                            </div>
                            <div class="form-group">
                                <label for="middle_name">Middle Name:</label>
                                <input id="middle_name" class="form-control" value="{{old('middle_name', $user->middle_name)}}" type="text" name="middle_name" placeholder="P" required>
                            </div>
                            <div class="form-group">
                                <label for="last_name">Last Name:</label>
                                <input id="last_name" class="form-control" value="{{old('last_name', $user->last_name)}}" type="text" name="last_name" placeholder="Dela Cruz" required>
                            </div>
                            <div class="form-group">
                                <label for="prc_no">PRC Number:</label>
                                <input id="prc_no" class="form-control" value="{{old('prc_no', $user->prc_no)}}" type="text" name="prc_no" placeholder="001234" required>
                            </div>
                            <div class="form-group">
                                <label for="position">Position:</label>
                                <input id="position" class="form-control" value="{{old('position', $user->position)}}" type="text" name="position" placeholder="Medical Technologist" required>
                            </div>
                            <div class="form-group">
                                <label for="middle_name">Email Address:</label>
                                <input id="middle_name" class="form-control" value="{{old('email', $user->email)}}" type="email" name="email" placeholder="jdelacruz@gmail.com">
                            </div>
                            <div class="form-group">
                                <label for="last_name">Password:</label>
                                <input id="last_name" class="form-control" type="password" name="password" required>
                            </div>

                            <div class="form-group">
                                <label for="my-select">Role</label>
                                <select id="my-select" class="form-control" name="role">
                                    <option value="P">Pathologist</option>
                                    <option value="MT">Med Tech</option>
                                </select>
                            </div>

                        </div>
                        <p></p>
                        <button class="btn btn-success" type="submit">{{isset($user->id) ? 'Update' : 'Save'  }}</button>
                        <a href="{{route('users.index')}}" class="btn btn-danger" type="button">Cancel</a>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">

                            <label for="formFile" class="form-label">E-Signature</label>
                            <input class="form-control" type="file" id="formFile" name="esign" {{isset($user->id) ? '' : 'required'}}>
                        </div>
                        @if(isset($user->id))
                        <div class="form-group">
                            <p>Current E-Sign:</p>
                            <img class="img-fluid w-50" src="{{asset('storage/'.$user->signature)}}" alt="">
                        </div>
                        @endif
                    </div>
                    <!--//col-->
                </div>
                <!--//row-->
            </form>

        </div>
        <!--//app-card-body-->

    </div>
    <!--//inner-->
</div>

@endsection

resources/views/users/index.blade.php
@extends('layout.app')

@section('content')
<nav aria-label="Page breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">Users</li>
    </ol>
</nav>
<a href="{{route('users.create')}}" class="btn btn-success btn-sm"><small>Add new</small></a>
<p></p>
<div class="app-card shadow-sm mb-4 border-left-decoration">
    <div class="inner">
        <div class="app-card-body p-4">
            <div class="row gx-5 gy-3">
                <div class="col-12 col-md-12 col-sm-12">

                    <table class="table table-light" id="users_table">
                        <thead class="thead-light">
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Role</th>
                                <th>Date Added</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($users as $user)
                            <tr>
                                <td>{{$user->id}}</td>
                                <td class="text-uppercase">{{$user->first_name}} {{$user->middle_name ?? $user->middle_name}} {{$user->last_name}}</td>
                                <td class="text-uppercase">{{$user->getRoleNames()[0]}}</td>
                                <td class="text-uppercase">{{$user->created_at}}</td>
                                <td>
                                    <form action="{{route('users.destroy', $user)}}" method="post">
                                        <a href="{{route('users.edit', $user)}}" class="btn btn-info" type="button">Edit</a>
                                        @csrf
                                        @method('DELETE')

                                        <button class="btn btn-danger" type="submit">Delete</button>
                                    </form>
                                </td>
                            </tr>
                            @empty
                            <tr>
                                <td colspan="6">No record found.</td>
                            </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
                <!--//col-->
            </div>
            <!--//row-->

        </div>
        <!--//app-card-body-->

    </div>
    <!--//inner-->
</div>

@endsection

@section('js')
<script>
    $(function() {
        $('#users_table').DataTable();

    })
</script>
@endsection