routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

use App\Http\Controllers\LabTestResultController;
use App\Http\Controllers\PatientController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PhysicianController;
use App\Http\Controllers\ResultController;
use App\Http\Controllers\BrandController;
use App\Http\Controllers\SpecimenController;
use App\Http\Controllers\TestController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\SettingController;

// Route::get('/mail/{id}', [LabTestResultController::class, 'mail_test'])->name('mail_test');


Route::middleware(['auth'])->group(function () {
    Route::get('/', function () {
        return view('layout.app');
    });


    Route::group(['middleware' => ['role:pathologist']], function () {
        Route::group(['prefix' => 'settings', 'as' => 'settings.'], function () {
            Route::get('/', [SettingController::class, 'index'])->name('index');
            Route::post('/update-facility', [SettingController::class, 'updateFacility'])->name('updateFacility');
            Route::post('/update-logo', [SettingController::class, 'updateLogo'])->name('updateLogo');
            Route::post('/update-auto-approve', [SettingController::class, 'updateAutoApprove'])->name('updateAutoApprove');
        });
        Route::resource('/users', UserController::class);
        Route::resource('/results', ResultController::class);
        Route::resource('/brands', BrandController::class);
        Route::resource('/specimens', SpecimenController::class);
        Route::resource('/tests', TestController::class);

        Route::group(['prefix' => 'lab-tests', 'as' => 'labTests.'], function () {
            Route::get('/', [LabTestResultController::class, 'index'])->name('index');
            Route::put('/{id}/approve', [LabTestResultController::class, 'approve'])->name('approve');
        });
    });
    Route::group(['middleware' => ['role:pathologist|medTech']], function () {
        Route::resource('/patients', PatientController::class);
        Route::group(['prefix' => 'patients', 'as' => 'patients.'], function () {
            Route::get('/{id}/vaccinations/', [PatientController::class, 'index_vax'])->name('index_vax');
            Route::get('/{id}/vaccinations/create', [PatientController::class, 'create_vax'])->name('create_vax');
            Route::post('/{id}/vaccinations/store', [PatientController::class, 'store_vax'])->name('store_vax');
            Route::get('/{id}/vaccinations/{vax_id}/edit', [PatientController::class, 'edit_vax'])->name('edit_vax');
            Route::put('/{id}/vaccinations/{vax_id}/update', [PatientController::class, 'update_vax'])->name('update_vax');
        });
        Route::resource('/physicians', PhysicianController::class);
        Route::group(['prefix' => 'lab-tests', 'as' => 'labTests.'], function () {
            Route::get('/', [LabTestResultController::class, 'index'])->name('index');
            Route::get('/{id}/show', [LabTestResultController::class, 'show'])->name('show');
            Route::get('/{id}/mail', [LabTestResultController::class, 'mail_patient'])->name('mail_patient');
            Route::put('/{id}/to-validate', [LabTestResultController::class, 'to_validate'])->name('to_validate');
        });
    });

    Route::group(['middleware' => ['role:medTech']], function () {

        Route::group(['prefix' => 'lab-tests', 'as' => 'labTests.'], function () {

            Route::get('/create', [LabTestResultController::class, 'create'])->name('create');
            Route::post('/store', [LabTestResultController::class, 'store'])->name('store');
            Route::get('/{id}/edit', [LabTestResultController::class, 'edit'])->name('edit');
            Route::put('/{id}/update', [LabTestResultController::class, 'update'])->name('update');
            Route::delete('/{id}/delete', [LabTestResultController::class, 'delete'])->name('delete');
        });
    });
});

Route::get('/{key}/pdf', [LabTestResultController::class, 'pdf'])->name('pdf');
Route::get('lab-tests/{key}/verify', [LabTestResultController::class, 'verify'])->name('verify');

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);

app/Models/MedTech.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class MedTech extends Model
{
    use HasFactory;

    protected $fillable = ['user_id', 'first_name', 'middle_name', 'last_name', 'suffix', 'license_no', 'signature', 'position'];
}

app/Http/Controllers/MedTechController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\MedTech;

class MedTechController extends Controller
{
    public function index()
    {
        $medteches = MedTech::all();
        return view('medteches.index', compact('medteches'));
    }

    public function create()
    {
        $MedTech = new MedTech();
        return view('medteches.form', compact('MedTech'));
    }

    public function store(Request $request)
    {
        MedTech::create($request->except('_token'));
        return redirect(\route('medteches.index'));
    }

    public function edit(MedTech $MedTech)
    {
        return view('medteches.form', compact('MedTech'));
    }

    public function update(Request $request, MedTech $MedTech)
    {
        $MedTech->update($request->except('_token'));
        return redirect(\route('medteches.index'));
    }

    public function destroy(MedTech $MedTech)
    {
        MedTech::destroy($MedTech->id);
        return redirect(\route('medteches.index'));
    }
}

resources/views/medteches/form.blade.php
@extends('layout.app')

@section('content')
<nav aria-label="Page breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item" aria-current="page"><a href="{{route('physicians.index')}}">Physicians</a></li>
        <li class="breadcrumb-item active" aria-current="page">Add new</li>
    </ol>
</nav>
<div class="app-card shadow-sm mb-4 border-left-decoration">
    <div class="inner">
        <div class="app-card-body p-4">
            <div class="row gx-5 gy-3">
                <div class="col-md-6 ">
                    <form action="{{isset($physician->id) ? route('physicians.update', $physician->id) :route('physicians.store')}}" method="post">
                        @csrf
                        @if(isset($physician->id))
                        @method('PUT')
                        @endif
                        <div class="row">
                            <div class="form-group">
                                <label for="first_name">First Name:</label>
                                <input id="first_name" class="form-control" value="{{old('first_name', $physician->first_name)}}" type="text" name="first_name" placeholder="Juan" required>
                            </div>
                            <div class="form-group">
                                <label for="middle_name">Middle Name:</label>
                                <input id="middle_name" class="form-control" value="{{old('middle_name', $physician->middle_name)}}" type="text" name="middle_name" placeholder="P.">
                            </div>
                            <div class="form-group">
                                <label for="last_name">Last Name:</label>
                                <input id="last_name" class="form-control" value="{{old('last_name', $physician->last_name)}}" type="text" name="last_name" placeholder="Dela Cruz" required>
                            </div>


                            <div class="form-group">
                                <label for="suffix">Suffix:</label>
                                <input id="suffix" class="form-control" value="{{old('suffix', $physician->suffix)}}" type="text" name="suffix" placeholder="MD" required>
                            </div>

                            <div class="form-group">
                                <label for="prc_no">PRC Number:</label>
                                <input id="prc_no" class="form-control" value="{{old('prc_no', $physician->prc_no)}}" type="text" name="prc_no" placeholder="12345" required>
                            </div>
                        </div>
                        <p></p>
                        <button class="btn btn-success" type="submit">Save</button>
                        <a href="{{route('physicians.index')}}" class="btn btn-danger" type="button">Cancel</a>
                    </form>
                </div>
                <div class="col-md-6">
                    <i class="fas fa-user-md fa-lg"></i>
                </div>
                <!--//col-->
            </div>
            <!--//row-->

        </div>
        <!--//app-card-body-->

    </div>
    <!--//inner-->
</div>

@endsection

resources/views/medteches/index.blade.php
@extends('layout.app')

@section('content')
<nav aria-label="Page breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">Med Technologist</li>
    </ol>
</nav>
<a href="{{route('medteches.create')}}" class="btn btn-success btn-sm"><small>Add new</small></a>
<p></p>
<div class="app-card shadow-sm mb-4 border-left-decoration">
    <div class="inner">
        <div class="app-card-body p-4">
            <div class="row gx-5 gy-3">
                <div class="col-12 col-md-12 col-sm-12">

                    <table class="table table-light" id="physicians_table">
                        <thead class="thead-light">
                            <tr>
                                <th>License No.</th>
                                <th>First name</th>
                                <th>Middle initial</th>
                                <th>Last Name</th>
                                <th>Suffix</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($medteches as $medtech)
                            <tr>
                                <td>{{$medtech->license_no}}</td>
                                <td class="text-uppercase">{{$medtech->first_name}}</td>
                                <td class="text-uppercase">{{$medtech->middle_name}}</td>
                                <td class="text-uppercase">{{$medtech->last_name}}</td>
                                <td class="text-uppercase">{{$medtech->suffix}}</td>
                                <td>
                                    <form action="{{route('medteches.destroy', $medtech)}}" method="post">
                                        <a href="{{route('medteches.edit', $medtech)}}" class="btn btn-info" type="button">Edit</a>
                                        @csrf
                                        @method('DELETE')

                                        <button class="btn btn-danger" type="submit">Delete</button>
                                    </form>
                                </td>
                            </tr>
                            @empty
                            <tr>
                                <td colspan="6">No record found.</td>
                            </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
                <!--//col-->
            </div>
            <!--//row-->

        </div>
        <!--//app-card-body-->

    </div>
    <!--//inner-->
</div>

@endsection

@section('js')
<script>
    $(function() {
        $('#physicians_table').DataTable();

    })
</script>
@endsection