routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

use App\Http\Controllers\LabTestResultController;
use App\Http\Controllers\PatientController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PhysicianController;
use App\Http\Controllers\ResultController;
use App\Http\Controllers\BrandController;
use App\Http\Controllers\SpecimenController;
use App\Http\Controllers\TestController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\SettingController;

// Route::get('/mail/{id}', [LabTestResultController::class, 'mail_test'])->name('mail_test');


Route::middleware(['auth'])->group(function () {
    Route::get('/', function () {
        return view('layout.app');
    });


    Route::group(['middleware' => ['role:pathologist']], function () {
        Route::group(['prefix' => 'settings', 'as' => 'settings.'], function () {
            Route::get('/', [SettingController::class, 'index'])->name('index');
            Route::post('/update-facility', [SettingController::class, 'updateFacility'])->name('updateFacility');
            Route::post('/update-logo', [SettingController::class, 'updateLogo'])->name('updateLogo');
            Route::post('/update-auto-approve', [SettingController::class, 'updateAutoApprove'])->name('updateAutoApprove');
        });
        Route::resource('/users', UserController::class);
        Route::resource('/results', ResultController::class);
        Route::resource('/brands', BrandController::class);
        Route::resource('/specimens', SpecimenController::class);
        Route::resource('/tests', TestController::class);

        Route::group(['prefix' => 'lab-tests', 'as' => 'labTests.'], function () {
            Route::get('/', [LabTestResultController::class, 'index'])->name('index');
            Route::put('/{id}/approve', [LabTestResultController::class, 'approve'])->name('approve');
        });
    });
    Route::group(['middleware' => ['role:pathologist|medTech']], function () {
        Route::resource('/patients', PatientController::class);
        Route::group(['prefix' => 'patients', 'as' => 'patients.'], function () {
            Route::get('/{id}/vaccinations/', [PatientController::class, 'index_vax'])->name('index_vax');
            Route::get('/{id}/vaccinations/create', [PatientController::class, 'create_vax'])->name('create_vax');
            Route::post('/{id}/vaccinations/store', [PatientController::class, 'store_vax'])->name('store_vax');
            Route::get('/{id}/vaccinations/{vax_id}/edit', [PatientController::class, 'edit_vax'])->name('edit_vax');
            Route::put('/{id}/vaccinations/{vax_id}/update', [PatientController::class, 'update_vax'])->name('update_vax');
        });
        Route::resource('/physicians', PhysicianController::class);
        Route::group(['prefix' => 'lab-tests', 'as' => 'labTests.'], function () {
            Route::get('/', [LabTestResultController::class, 'index'])->name('index');
            Route::get('/{id}/show', [LabTestResultController::class, 'show'])->name('show');
            Route::get('/{id}/mail', [LabTestResultController::class, 'mail_patient'])->name('mail_patient');
            Route::put('/{id}/to-validate', [LabTestResultController::class, 'to_validate'])->name('to_validate');
        });
    });

    Route::group(['middleware' => ['role:medTech']], function () {

        Route::group(['prefix' => 'lab-tests', 'as' => 'labTests.'], function () {

            Route::get('/create', [LabTestResultController::class, 'create'])->name('create');
            Route::post('/store', [LabTestResultController::class, 'store'])->name('store');
            Route::get('/{id}/edit', [LabTestResultController::class, 'edit'])->name('edit');
            Route::put('/{id}/update', [LabTestResultController::class, 'update'])->name('update');
            Route::delete('/{id}/delete', [LabTestResultController::class, 'delete'])->name('delete');
        });
    });
});

Route::get('/{key}/pdf', [LabTestResultController::class, 'pdf'])->name('pdf');
Route::get('lab-tests/{key}/verify', [LabTestResultController::class, 'verify'])->name('verify');

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);

app/Models/Specimen.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Specimen extends Model
{
    use HasFactory, SoftDeletes;
    protected $fillable = ['description'];
}

app/Http/Controllers/SpecimenController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Specimen;

class SpecimenController extends Controller
{
    public function index(Specimen $specimen)
    {
        $specimens = Specimen::all();
        return view('specimens.index', compact('specimens', 'specimen'));
    }

    public function store(Request $request)
    {
        Specimen::create($request->except('_token'));
        return redirect(\route('specimens.index'));
    }
    public function edit(Specimen $specimen)
    {
        $specimens = Specimen::all();
        return view('specimens.index', compact('specimens', 'specimen'));
    }


    public function update(Request $request, Specimen $specimen)
    {
        $specimen->update($request->except('_token'));
        return redirect(\route('specimens.index'));
    }
    public function destroy(Specimen $specimen)
    {
        Specimen::destroy($specimen->id);
        return redirect(\route('specimens.index'));
    }
}

resources/views/specimens/index.blade.php
@extends('layout.app')

@section('content')
<nav aria-label="Page breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">Specimens</li>
    </ol>
</nav>
<div class="row">
    <div class="col-md-4 col-sm-12">
        <div class="app-card shadow-sm mb-4 border-left-decoration">
            <div class="inner">
                <div class="app-card-body p-4">
                    <div class="row gx-5 gy-3">
                        <div class="col-md col-sm-12">
                            <form method="POST" action="{{isset($specimen->id) ? route('specimens.update', $specimen) : route('specimens.store')}}">
                                @csrf
                                @if(isset($specimen->id))
                                @method('PUT')
                                @endif
                                <div class="form-group">
                                    <label for="description">Description</label>
                                    <input id="description" class="form-control" value="{{old('name', $specimen->description)}}" type="text" name="description" placeholder="Oropharyngeal swab">
                                </div>
                                <p></p>
                                <button class="btn btn-primary" type="submit">Save</button>
                                @if(isset($specimen->id))
                                <a href="{{route('specimens.index')}}" class="btn btn-warning" type="button">Cancel</a>
                                @endif
                            </form>
                        </div>
                        <!--//col-->
                    </div>
                    <!--//row-->

                </div>
                <!--//app-card-body-->

            </div>
            <!--//inner-->
        </div>

    </div>
    <div class="col-md col-sm-12">
        <table class="table table-light table-hover" id="specimens_table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Description</th>
                    <th>Date added</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @forelse($specimens as $specimen)
                <tr>
                    <td>{{$specimen->id}}</td>
                    <td>{{$specimen->description}}</td>
                    <td>{{$specimen->created_at}}</td>
                    <td>
                        <form action="{{route('specimens.destroy', $specimen)}}" method="POST">
                            <a href="{{route('specimens.edit', $specimen)}}" class="btn btn-primary" type="button">Edit</a>
                            @csrf
                            @method("DELETE")
                            <button class="btn btn-danger" type="submit">Delete</button>
                        </form>
                    </td>
                </tr>
                @empty
                <tr>
                    <td colspan="4">No record found.</td>
                </tr>
                @endforelse
            </tbody>
        </table>

    </div>
</div>
@endsection

@section('js')
<script>
    $(function() {
        $('#specimens_table').DataTable()
    })
</script>
@endsection